services:
  aiden017-database:
    build:
      context: .
    container_name: aide017-database-service
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: aide017-database-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: aiden017database
    ports:
      - "21713:27017"
    volumes:
      - aiden017-database-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: aiden017-database-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aiden017database
    ports:
      - "5112:5432"
    volumes:
      - aiden017-database-postgresql:/data/db/postgresql

volumes:
  aiden017-database-mongodb:
    driver: local
  aiden017-database-postgresql:
    driver: local
